### PR TITLE
Fix export power saving data to kml

### LINKED ISSUE #10: Export power saving data in CSV and KML output
In the later stages of the pilot, we added power savings data capture in OneBusAway for whether the user had "power savings mode" activated, and a few other related fields.

We should export that data to CSV and KML output with the other data.

### PR DESCRIPTION
**Pull request by welozano**
Closes #10

### CODE REVIEW

File: src/main/java/edu/usf/cutr/tba/io/KmlFileWriter.java [hunk 1]
```diff
@@ -283,6 +283,31 @@ private String getLocationPlacemark(TravelBehaviorRecord tbr, boolean origin) {
             duration = "<strong>" + "Activity Duration: </strong> Bad time data\n<br />";
         }
 
+        // Validate battery optimization feature before formatting
+        String strIgnoringBatteryOptimization;
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/tba/io/KmlFileWriter.java:287]: You can remove the `str` prefix for all new variables - `ignoringBatteryOptimization`

**Review by barbeau — COMMENTED** [review]
Thanks @welozano! This looks good - just one comment in-line.

**Review by barbeau — APPROVED** [review]
LGTM, thanks!
