### PR TITLE
fix: Check timestamp format during export

### LINKED ISSUE #24: Crash on java.lang.NumberFormatException during export
**Describe the bug**

Running on exporting the production data:

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "XXXXX"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at edu.usf.cutr.tba.utils.QueryDocumentSnapshotDeviceComparator.getDeviceComparableTime(QueryDocumentSnapshotDeviceComparator.java:48)
	at edu.usf.cutr.tba.utils.QueryDocumentSnapshotDeviceComparator.compare(QueryDocumentSnapshotDeviceComparator.java:35)
	at edu.usf.cutr.tba.utils.QueryDocumentSnapshotDeviceComparator.compare(QueryDocumentSnapshotDeviceComparator.java:29)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at edu.usf.cutr.tba.manager.TravelBehaviorDataAnalysisManager.processUserById(TravelBehaviorDataAnalysisManager.java:121)
	at edu.usf.cutr.tba.manager.TravelBehaviorDataAnalysisManager.analyzeAllTravelBehaviorData(TravelBehaviorDataAnalysisManager.java:89)
	at edu.usf.cutr.tba.manager.TravelBehaviorDataAnalysisManager.processData(TravelBehaviorDataAnalysisManager.java:73)
	at edu.usf.cutr.tba.ProcessorMain.main(ProcessorMain.java:120)
```

...where `XXXXX` is a long alpha numeric string.

**To Reproduce**
1. Run with command-line parameters `-keyFile "path/to/keyfile/key.json" -skipKMZ -outputDir myOutput`

**Expected behavior**
Export should complete without a crash

**Actual behavior**
Application crashed during export

**Desktop (please complete the following information):**
Master branch as of https://github.com/CUTR-at-USF/travel-behavior-analysis/commit/62ad9aab3383d9ec3cb9cf3fbb31d326a61e343e running on Windows 7 Enterprise with JDK 8.

### PR DESCRIPTION
**Pull request by welozano**
Closes #24 
Functions to validate if a time stamp is a valid long value where added. If the given time stamp is not a valid long value, then the best option between the prefix value of the string or Lon.MIN_VALUES is used as time stamp.

### CODE REVIEW

File: src/main/java/edu/usf/cutr/tba/utils/StringUtils.java [hunk 1]
```diff
@@ -84,4 +85,50 @@ public static String validateAndParseOutputPath(String newPath) {
...
+        return Long.parseLong(timeStamp);
+    }
+
+    /**
+     * If the provided timeStamp is parsable return the same string. If it is not parsable, the function will find the
+     * best timeStamp option between a prefix value of the provided string or the MIN_VALUE of the Long class.
+     * @param timeStamp string containing a possible time stamp
+     * @return string with a parsable time stamp
+     */
+    public static String parsableTimeStamp(String timeStamp) {
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/tba/utils/StringUtils.java:118]: I believe this method is unused and can be removed?

File: src/main/java/edu/usf/cutr/tba/utils/StringUtils.java [hunk 2]
```diff
@@ -84,4 +85,50 @@ public static String validateAndParseOutputPath(String newPath) {
         }
     }
 
+    /**
+     * If stringTimestamp is parsable to Long then return its long value, it it is not parsable, the function will find
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/tba/utils/StringUtils.java:89]: typo - "it it is not..."

File: src/main/java/edu/usf/cutr/tba/utils/StringUtils.java [hunk 3]
```diff
@@ -84,4 +85,50 @@ public static String validateAndParseOutputPath(String newPath) {
...
+     */
+    public static long timeStampToLong(String timeStamp) {
+        if (!NumberUtils.isParsable(timeStamp)) {
+            // The timestamp must be a random string with a numeric prefix, get the prefix
+            int indexDash = timeStamp.indexOf("-");
+            if (indexDash == -1) {
+                // Dash not found, return MIN_VALUE
+                return Long.MIN_VALUE;
+            }
+            timeStamp = timeStamp.substring(0 , indexDash);
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/tba/utils/StringUtils.java:102]: The prefix isn't a timestamp, so I'd avoid assigning it to the `timestamp` variable here to avoid future confusion.

File: src/main/java/edu/usf/cutr/tba/utils/StringUtils.java (hunk 1 above)
Comment (barbeau) [reply src/main/java/edu/usf/cutr/tba/utils/StringUtils.java:118]: Actually, looks like this is used too, but is almost a line-by-line duplicate of the above method (at first I thought this was a left-over first draft). Can you combine these methods to avoid duplicating this much code? Maybe passing in the entire `DeviceInformation` object and doing the null check within the method would help?

**Review by barbeau — COMMENTED** [review]
Thanks @welozano! Generally looks good, some comments in-line.

File: src/main/java/edu/usf/cutr/tba/utils/StringUtils.java (hunk 2 above)
Comment (welozano) [reply src/main/java/edu/usf/cutr/tba/utils/StringUtils.java]: The function was removed.

File: src/main/java/edu/usf/cutr/tba/utils/StringUtils.java (hunk 3 above)
Comment (welozano) [reply src/main/java/edu/usf/cutr/tba/utils/StringUtils.java]: I added a local variable for the prefix. substring.

**Review by barbeau — APPROVED** [review]
Thanks @welozano!
